version: 2.1
orbs:
  go: circleci/go@3
jobs:
  cci-agent-setup:
    executor:
      name: go/default
      tag: "1.23-node"
    steps:
      - checkout
workflows:
  cci-agent-setup:
    jobs:
      - cci-agent-setup
